// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRi0XbHQqfnUQ7o9aiucaOk8iN67ppU5Q',
    appId: '1:32010850041:web:5366b32c5479eb01839c28',
    messagingSenderId: '32010850041',
    projectId: 'hosting-9603e',
    authDomain: 'hosting-9603e.firebaseapp.com',
    storageBucket: 'hosting-9603e.appspot.com',
    measurementId: 'G-SK8JE3HV64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EGU3LGwVEzY3jzBnprwqlRzt4rgwaek',
    appId: '1:32010850041:android:986298788e6a3ce8839c28',
    messagingSenderId: '32010850041',
    projectId: 'hosting-9603e',
    storageBucket: 'hosting-9603e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8Fx63k_flskNsXMzSFmFSwYIMoThyeI',
    appId: '1:32010850041:ios:00f5dc25f83aa1d5839c28',
    messagingSenderId: '32010850041',
    projectId: 'hosting-9603e',
    storageBucket: 'hosting-9603e.appspot.com',
    iosClientId: '32010850041-fie0qn8cjg4cb1e5hohroid3af2fs4sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hosting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8Fx63k_flskNsXMzSFmFSwYIMoThyeI',
    appId: '1:32010850041:ios:00f5dc25f83aa1d5839c28',
    messagingSenderId: '32010850041',
    projectId: 'hosting-9603e',
    storageBucket: 'hosting-9603e.appspot.com',
    iosClientId: '32010850041-fie0qn8cjg4cb1e5hohroid3af2fs4sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hosting',
  );
}
